In [1]:
a = [[0,1,2]]*8
a

[[0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2],
 [0, 1, 2]]

In [2]:
import numpy
L_a=[list(x) for x in numpy.array(numpy.meshgrid(*a)).T.reshape(-1,len(a))]

In [3]:
L_a

[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0],
 [0, 2, 0, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 0, 0, 0, 0, 0],
 [1, 2, 0, 0, 0, 0, 0, 0],
 [2, 0, 0, 0, 0, 0, 0, 0],
 [2, 1, 0, 0, 0, 0, 0, 0],
 [2, 2, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 0, 0, 0, 0],
 [0, 2, 1, 0, 0, 0, 0, 0],
 [1, 0, 1, 0, 0, 0, 0, 0],
 [1, 1, 1, 0, 0, 0, 0, 0],
 [1, 2, 1, 0, 0, 0, 0, 0],
 [2, 0, 1, 0, 0, 0, 0, 0],
 [2, 1, 1, 0, 0, 0, 0, 0],
 [2, 2, 1, 0, 0, 0, 0, 0],
 [0, 0, 2, 0, 0, 0, 0, 0],
 [0, 1, 2, 0, 0, 0, 0, 0],
 [0, 2, 2, 0, 0, 0, 0, 0],
 [1, 0, 2, 0, 0, 0, 0, 0],
 [1, 1, 2, 0, 0, 0, 0, 0],
 [1, 2, 2, 0, 0, 0, 0, 0],
 [2, 0, 2, 0, 0, 0, 0, 0],
 [2, 1, 2, 0, 0, 0, 0, 0],
 [2, 2, 2, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0],
 [0, 1, 0, 1, 0, 0, 0, 0],
 [0, 2, 0, 1, 0, 0, 0, 0],
 [1, 0, 0, 1, 0, 0, 0, 0],
 [1, 1, 0, 1, 0, 0, 0, 0],
 [1, 2, 0, 1, 0, 0, 0, 0],
 [2, 0, 0, 1, 0, 0, 0, 0],
 [2, 1, 0, 1, 0, 0, 0, 0],
 [2, 2, 0, 1, 0, 0, 0, 0],
 [0, 0, 1, 1, 0, 0, 0, 0],
 

In [4]:
numpy.array(numpy.meshgrid(*a)).T.reshape(-1,len(a))

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 2, 0, ..., 0, 0, 0],
       ...,
       [2, 0, 2, ..., 2, 2, 2],
       [2, 1, 2, ..., 2, 2, 2],
       [2, 2, 2, ..., 2, 2, 2]])

In [5]:
numpy.meshgrid(*a)

[array([[[[[[[[0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]],
 
             [[0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]],
 
             [[0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]]],
 
 
            [[[0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]],
 
             [[0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]],
 
             [[0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]]],
 
 
            [[[0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]],
 
             [[0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]],
 
             [[0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]]]],
 
 
 
           [[[[0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]],
 
             [[0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]],
 
             [[0, 0, 0],
              [0, 0, 0],
              [0, 0, 0]]],
 
 
            [[[0, 0, 0],
              [0, 0, 0],

In [6]:
list(numpy.array(numpy.meshgrid(*a)).T.reshape(-1, 8))

[array([0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 1, 0, 0, 0, 0, 0, 0]),
 array([0, 2, 0, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 0, 0, 0, 0]),
 array([1, 1, 0, 0, 0, 0, 0, 0]),
 array([1, 2, 0, 0, 0, 0, 0, 0]),
 array([2, 0, 0, 0, 0, 0, 0, 0]),
 array([2, 1, 0, 0, 0, 0, 0, 0]),
 array([2, 2, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 1, 0, 0, 0, 0, 0]),
 array([0, 1, 1, 0, 0, 0, 0, 0]),
 array([0, 2, 1, 0, 0, 0, 0, 0]),
 array([1, 0, 1, 0, 0, 0, 0, 0]),
 array([1, 1, 1, 0, 0, 0, 0, 0]),
 array([1, 2, 1, 0, 0, 0, 0, 0]),
 array([2, 0, 1, 0, 0, 0, 0, 0]),
 array([2, 1, 1, 0, 0, 0, 0, 0]),
 array([2, 2, 1, 0, 0, 0, 0, 0]),
 array([0, 0, 2, 0, 0, 0, 0, 0]),
 array([0, 1, 2, 0, 0, 0, 0, 0]),
 array([0, 2, 2, 0, 0, 0, 0, 0]),
 array([1, 0, 2, 0, 0, 0, 0, 0]),
 array([1, 1, 2, 0, 0, 0, 0, 0]),
 array([1, 2, 2, 0, 0, 0, 0, 0]),
 array([2, 0, 2, 0, 0, 0, 0, 0]),
 array([2, 1, 2, 0, 0, 0, 0, 0]),
 array([2, 2, 2, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 1, 0, 0, 0, 0]),
 array([0, 1, 0, 1, 0, 0, 0, 0]),
 array([0, 2, 

In [7]:
len(numpy.array(numpy.meshgrid(*a)).T.reshape(-1, 8))

6561

In [8]:
def bai2(x ,y):
    if x > y:
        return "x < y"

    count = 0

    if x == y:
        return count

    while(True):
        print(x, y)
    
        if x * 2 == y or x - 1 == y:
            count += 1
            break
        else:
            if x < y:
                x *= 2
            else:
                x -= 1
            count += 1

    return count

print(bai2(1, 5))

1 5
2 5
4 5
8 5
7 5
6 5
6
